Improves defguard to raise closer to existing constructs.
Note that in order to accomplish full parity with compiler
warnings, we switched out unquoting the finished macro into a
quoted `defmacro`, in favor of define/4. I'm pretty sure this is
because that's because since we're still in Kernel land we're
using the bootstrapped `defmacro`.

The original implementation would not omit warnings when it
overrode an existing local macro. This is now tested for.

In summary, the errors and warning omitted by bad `defguard`
formulations are:

Not using a proper call (`name(args)`) will raise an:
  ArgumentError: invalid syntax in defguard
similar to existing `def`s.

Defining a guard that shadows things should raise/warn:

  Shadowing an imported macro:
    warning: unused import <imported>
  just like current shadowing.

  Shadowing an existing def/defp/defmacrop:
    CompileError: defmacro <guard> already defined as <existing>
  just like current mismatched redefinitions.

  Shadowing an existing macro:
    warning: this clause cannot match because a previous clause...
  just like current redefinitions.

No implementation (just `defguard name(args)`):
  warning: implementation not provided for predefined defguard
similar to existing body-less `def`s. Just like them, this doesn't
define anything, rather than providing some default `nil` impl.

A block provided with/without an implementation:
  CompileError: undefined function defguard/2
just like other second-gen `def`s--defoverridable, for example.