Fix cryptic error when defimpl is defined without :for option
When defimpl/2 is defined outside a module without a :for option, such as in the code bellow,
it will five a cryptic error.

defprotocol A do
  def ok(term)
end

defimpl A do
  def ok(term), do: {:ok, term}
end

BEFORE FIX:
19:42:16.595 [error] Task #PID<0.187.0> started from #PID<0.95.0> terminating
** (CaseClauseError) no case clause matching: {:error, :not_a_protocol}
    (mix 1.11.2) lib/mix/tasks/compile.protocols.ex:141: Mix.Tasks.Compile.Protocols.consolidate/4
    (elixir 1.11.2) lib/task/supervised.ex:90: Task.Supervised.invoke_mfa/2
    (elixir 1.11.2) lib/task/supervised.ex:35: Task.Supervised.reply/5
    (stdlib 3.13.2) proc_lib.erl:226: :proc_lib.init_p_do_apply/3
Function: #Function<9.81221892/0 in Mix.Tasks.Compile.Protocols.consolidate/6>
    Args: []
** (EXIT from #PID<0.95.0>) an exception was raised:
    ** (CaseClauseError) no case clause matching: {:error, :not_a_protocol}
        (mix 1.11.2) lib/mix/tasks/compile.protocols.ex:141: Mix.Tasks.Compile.Protocols.consolidate/4
        (elixir 1.11.2) lib/task/supervised.ex:90: Task.Supervised.invoke_mfa/2
        (elixir 1.11.2) lib/task/supervised.ex:35: Task.Supervised.reply/5
        (stdlib 3.13.2) proc_lib.erl:226: :proc_lib.init_p_do_apply/3

AFTER FIX:
== Compilation error in file lib/broken2.ex ==
** (ArgumentError) defimpl/1 expects a :for option when declared outside a module
    (elixir 1.12.0-dev) lib/kernel.ex:4846: Kernel."MACRO-defimpl"/4
    (elixir 1.12.0-dev) expanding macro: Kernel.defimpl/2
    lib/broken2.ex:5: (file)